### ISSUE TITLE
How can I contribute to the descriptions of the roles that are found on https://en.tohe.cc/Roles.html?

### ISSUE THREAD

**Issue by NFeruch** [KARPED1EM/TownOfHostEdited#101]
I want to contribute to make the descriptions easier to understand/more comprehensive, how can I do so?

**Comment by KARPED1EM** [comment]
https://crowdin.com/project/tohe

**Comment by KARPED1EM** [comment]
and
Please DO NOT use any quotation marks (single and double) or your translation will be withdrawn.
Please DO NOT use any quotation marks (single and double) or your translation will be withdrawn.
Please DO NOT use any quotation marks (single and double) or your translation will be withdrawn.
