### ISSUE TITLE
官网一些翻译问题（持续犯病中

### ISSUE THREAD

**Issue by Sand-and-Beans** [KARPED1EM/TownOfHostEdited#103]
今晚翻了一番英文官网，发现了一点问题 =D

![2023-04-18](https://user-images.githubusercontent.com/129944434/232796056-09c05642-3f51-4f0d-be63-80d9490b6481.png)
这个应该是打错了吧，应该是screen（进阶>快捷键）

![2023-04-18 (1)](https://user-images.githubusercontent.com/129944434/232796279-36e7b67a-5f90-46bf-bfb3-e5d588d02966.png)
这个理论上来讲是个语法错误，应该将“I”之前的“,”变为“.”（介绍>关于）

![2023-04-18 (2)](https://user-images.githubusercontent.com/129944434/232796898-dbca1b28-b35c-4efd-835e-3dd036777dbc.png)
“ban”的倒数第二个字母是“a“，元音，所以应该双写”n“，正确的拼写是：banned（进阶>封禁名单）

![2023-04-18 (3)](https://user-images.githubusercontent.com/129944434/232797246-70fcebc2-b8f0-4199-9fa5-16be78a45583.png)
这应该也是打错了，应该是it（常见问题>下载了模组后依然是原版）

![2023-04-18 (4)](https://user-images.githubusercontent.com/129944434/232797972-a5a59288-c0cf-433b-a9b6-0d9307d57eb2.png)
语法问题，应该把”there“前面的”,“改为”.“，T要大写（常见问题>我们有一个重要的更新，请更新模组）

**Comment by KARPED1EM** [comment]
[Markdown.zip](https://github.com/KARPED1EM/TownOfHostEdited/files/11262591/Markdown.zip)

**Comment by Sand-and-Beans** [comment]
> [Markdown.zip](https://github.com/KARPED1EM/TownOfHostEdited/files/11262591/Markdown.zip)

[Markdown.zip](https://github.com/KARPED1EM/TownOfHostEdited/files/11262764/Markdown.zip)
