### ISSUE TITLE
Host Gets frozen and more bugs + Ideas!

### ISSUE THREAD

**Issue by AirConditionunit** [KARPED1EM/TownOfHostEdited#106]
i freeze for about 20 seconds after i join back from a game and the whole lobby gets effected by it and if i touch my mouse or anything then the whole window becomes a not responding mess

**Comment by KARPED1EM** [comment]
## Idea
1) Pelicans as neutral no longer need to be weakened.
2) Please create a separate issue for submissions regarding a new role
3) command: /n all
4) All command and msgs from the client are sent globally to all players and cannot be intercepted.

## bug：
1）Check video

https://user-images.githubusercontent.com/89320463/233297054-0bfd68aa-3a5f-419f-a909-9c40b609797f.mp4


2) Tens of thousands of players in TOHE don't have this problem
3) Unable

**Comment by KARPED1EM** [comment]
> > ## Idea
> > 
> > 1. Pelicans as neutral no longer need to be weakened.
> > 2. Please create a separate issue for submissions regarding a new role
> > 3. command: /n all
> > 4. All command and msgs from the client are sent globally to all players and cannot be intercepted.
> > 
> > ## bug：
> > 1）Check video
> > Demo_x264.mp4
> > 2. Tens of thousands of players in TOHE don't have this problem
> > 3. Unable
> 
> Hey do you mind watching [This](https://drive.google.com/file/d/1nGgSSVFMX7tSU0qApQcIVXBRSj2eT1q0/view?usp=sharing) Video about the sheriff and arsonist glitch? for me this glitch is clear (Its not just arsonist its every role)
> 
> ### **EDIT!**
> ive tested it out it seems you switched around the individual and none options because i was only able to kill if it was on none

Fixed
