### ISSUE TITLE
English

### ISSUE THREAD

**Issue by borjita2019** [KARPED1EM/TownOfHostEdited#11]
Please do a translation to english. I can't understand anything.

请翻译成英文。我什么都听不懂。

**Comment by KARPED1EM** [comment]
Terribly sorry.
This mod is just for learning C#.
We have no capability to do a  translations for other languages.
btw, We'd also love to find someone who can help us translate mods

**Comment by borjita2019** [comment]
i could translate it into spanish, but i cant understand japanese

**Comment by KARPED1EM** [comment]
It’s actually in chinese. Our team is too small to even have an english translation.
Maybe we need to wait for a while to find someone who can help us translate into English, and then consider other language translations.
