### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by Sand-and-Beans** [KARPED1EM/TownOfHostEdited#110]
19:55:18（时间）
网红消息从紧急新闻变成了系统消息，对游戏影响不大，就是呃
[LogOutput.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11295888/LogOutput.log)

**Comment by KARPED1EM** [comment]
这是个严重的bug，会导致网红技能几乎失效，目前已经在Dev版本修复
