### ISSUE TITLE
Bug+1

### ISSUE THREAD

**Issue by Sand-and-Beans** [KARPED1EM/TownOfHostEdited#112]
隐蔽者开启小黑人技能后依然无法恢复（报告、拍灯、冷却结束）

![2023-04-22](https://user-images.githubusercontent.com/129944434/233783802-8baaaa1f-1f2e-477f-8c72-bc6e8428d432.png)
↑发起了隐蔽技能，没有结束

[LogOutput.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11301303/LogOutput.log)
↑日志

**Comment by KARPED1EM** [comment]
![image](https://user-images.githubusercontent.com/89320463/233784902-cf9b09ad-f275-4d1e-8203-a198859cbf86.png)

**Comment by KARPED1EM** [comment]
![image](https://user-images.githubusercontent.com/89320463/233784927-51f1bc86-8392-427e-9944-c0c6ab85bdd1.png)
