### ISSUE TITLE
Where is port.txt?

### ISSUE THREAD

**Issue by ykundesu** [KARPED1EM/TownOfHostEdited#116]
While check the source code, I confirmed that Resources/config/port.txt contained information such as IP address.
But there was no such file.
Where is port.txt?

**Comment by KARPED1EM** [comment]
Too many people were trying to atack our servers, so we removed this file.

**Comment by ykundesu** [comment]
This project is under the GPL and must not be removed.
The GPL requires that the source code must match that of the release.
Or is there a reason why it is permitted under the license?

**Comment by KARPED1EM** [comment]
That's not source code, that's a configuration file.

**Comment by KARPED1EM** [comment]
[Port.txt](https://github.com/KARPED1EM/TownOfHostEdited/files/11319126/Port.txt)

**Comment by KARPED1EM** [comment]
The project works fine without this file. And everyone can create or modify this configuration file at will

**Comment by KARPED1EM** [comment]
same as translation file

**Comment by ykundesu** [comment]
For now, the repository itself is GPL. Since this configuration file is in the release, I believe we need to make the configuration file available to the public.
No?

**Comment by KARPED1EM** [comment]
kk, good to know

**Comment by KARPED1EM** [comment]
https://github.com/KARPED1EM/TownOfHostEdited/blob/TOHE/Resources/Config/Port.txt

**Comment by ykundesu** [comment]
Thank you.
