### ISSUE TITLE
Creation of my own mod

### ISSUE THREAD

**Issue by dabao40** [KARPED1EM/TownOfHostEdited#119]
Hello, the contributor and the author of this programm @KARPED1EM. I have recently been working on my own project, which is also known as The Other Roles GM IA (yup, I'm making another version of The Other Roles). Unfortunately, I cannot find my way through my programm not only because both me and my team are teenagers and we know very little about programming using C# but also because that I do not know how to run my programm. I have tried to contact you privately, but there's something wrong with the Gmail that you have posted on your profile. Thank you very much for your participation, and we sincerely appreciate your work.

**Comment by KARPED1EM** [comment]
nice to meet u
there is no wrong with my gmail link ig
heres my email => leever.zzz@gmail.com
btw the only dev of TOHE is just me and im a teen too
so nvm, I’m with you.

**Comment by dabao40** [comment]
Sorry for not contacting you immediately when you gave me the response. I had tried to send you an email using the address that you had mentioned above. However, the system said that your server had retrieved my letter because it thought that my emails are rubbish mails and therefore, they had returned it. I'm very sorry about that. Maybe you can try receiving my letters using your email?

**Comment by dabao40** [comment]
By the way, you can try creating a discussion in my own repository, [TheOtherRolesGMIA](https://github.com/dabao40/TheOtherRolesGMIA), since the email thing is not working (I've mentioned it above).

> nice to meet u there is no wrong with my gmail link ig heres my email => [leever.zzz@gmail.com](mailto:leever.zzz@gmail.com) btw the only dev of TOHE is just me and im a teen too so nvm, I’m with you.

**Comment by KARPED1EM** [comment]
哥们你国人吧
你加个q或者wx也比这方便呐

**Comment by dabao40** [comment]
addd

> 哥们你国人吧 你加个q或者wx也比这方便呐
