### ISSUE TITLE
what are the steps to compile the source code for TOH?

### ISSUE THREAD

**Issue by Wealthtwin** [KARPED1EM/TownOfHostEdited#12]
When I try to compile the code, it gives a lot CS0246 errors. Its always 1377 errors everytime

**Comment by KARPED1EM** [comment]
We changed local references to package references.
You can try to add a nuget source in your project: https://nuget.bepinex.dev/v3/index.json
Or you can use [.csproj file](https://github.com/tukasa0001/TownOfHost/blob/main/TownOfHost.csproj) in original toh.

**Comment by Wealthtwin** [comment]
When I try to compile the code in Visual Studio, it gives a lot of error messages mostly error CS0246 The type or namespace name 'AmongUs' could not be found (are you missing a using directive or an assembly reference?).  More than 1000 of these types of errors.

**Comment by KARPED1EM** [comment]
yeah, do you add https://nuget.bepinex.dev/v3/index.json in nuget source?

**Comment by Wealthtwin** [comment]
I added it and now am getting this error. 
error MSB4018: The "GenerateInteropAssembliesTask" task failed unexpectedly.

also I can see exclamation marks near all the nuget packages

**Comment by KARPED1EM** [comment]
Sorry, it's first time i meet this problem.
try download [this file](https://github.com/tukasa0001/TownOfHost/blob/main/TownOfHost.csproj) overwrite the local `TownOfHost.csproj` file may sovle it, i guess.

~~tbn i never use C# or VS before.~~

**Comment by Wealthtwin** [comment]
same problem. I also never used VS before. The dev of this mod didnt want to tell me how to compile it. Thats why I'm asking you. I think the error might be because I have 64 bit windows.

**Comment by KARPED1EM** [comment]
Yep, they don't seem to accept issues, but a discord form.

one my friend also got the same error as yours a few days ago. We have tried many ways but it still doesn't work.

than i found this:https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb4018

But i don't think it's because 64 bit windows.
(it's work well on my 64 bit pc.)

冒昧问下，请问你是中国人吗？（看你似乎star了中文项目）

**Comment by Wealthtwin** [comment]
Im not chinese, I would have translated and talked to you if I have to because no one was helping me with this mod, so yeah thanks for helping me

**Comment by KARPED1EM** [comment]
I found answer i guess
seems like i forgot to upload the setting file
try cloning and compiling again please
