### ISSUE TITLE
Found some bugs (will be editing every bug i find here)

### ISSUE THREAD

**Issue by AirConditionunit** [KARPED1EM/TownOfHostEdited#120]
**(1): Pelican Name text (screenshot token from nintendo switch)**
![2023042815364500_s](https://user-images.githubusercontent.com/120294277/235254870-dfac1d8c-3a7d-41d6-8940-2e6f321840be.jpg)

(any more bugs i find i will put it here)

Edit: Bug 2: non-host players as ghosts cannot see amount of tasks/douces/bullets/etc everyone has

**Comment by KARPED1EM** [comment]
Bug1 is coz the host modified the game files by mistake

**Comment by KARPED1EM** [comment]
bug2 has been fixed in dev version
