### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by AirConditionunit** [KARPED1EM/TownOfHostEdited#121]
everytime i try to open tohe after update a black command type window opens up for a few secs and then it goes in TOHE and it doesnt let me sigh in

**Comment by KARPED1EM** [comment]
[steam_appid.txt](https://github.com/KARPED1EM/TownOfHostEdited/files/11362060/steam_appid.txt)
try put this file to root directory

**Comment by KARPED1EM** [comment]
its console of bepinex, new ver of bepinex enable the console by default, nvm just leave it alone
