### ISSUE TITLE
[QUESTION] Vampire bite ignores medic shield?

### ISSUE THREAD

**Issue by NFeruch** [KARPED1EM/TownOfHostEdited#124]
Currently, I think the vampire bite ignores the medics shield. Is this intentional? Should this be changed?

**Comment by NFeruch** [comment]
Same thing with the pelican, the pelican should not be able to eat those that are shielded

**Comment by KARPED1EM** [comment]
Vampire kills are special kills. We all know shields don't prevent shock death

**Comment by KARPED1EM** [comment]
This is my understanding of the game

**Comment by NFeruch** [comment]
Ok, I think it's fair that the vampire can ignore the medic shield.

What about pelican though? I feel like the shield should protect against the pelican, otherwise the medic is a little bit useless

If there is a pelican and a vampire, the medic will only work against 1 imposter. Seems not strong enough

**Comment by KARPED1EM** [comment]
Game settings generally won't change anymore. Unless there is feedback from a large number of users
