### ISSUE TITLE
Lots of Bugs

### ISSUE THREAD

**Issue by AirConditionunit** [KARPED1EM/TownOfHostEdited#130]
- innocent black screens after the first meeting

- Knight (Original) role description overrides blood knight (New role) role description i have this problem with the beartrap that i renamed "Sticky Bait" now everytime i type "/r sticky bait" it shows me the bait desc

- and dictator has a kill count on the match results message (if they vote)

**Comment by KARPED1EM** [comment]
1. Cannot be fixed coz of the host-only mod
2. Fixed
3. Not a bug

**Comment by KARPED1EM** [comment]
![image](https://user-images.githubusercontent.com/89320463/236397593-68654ff5-709a-4c2e-a320-9bb0e6e75794.png)

**Comment by KARPED1EM** [comment]
Same problem as this one. ↑
Even host-only mods do a lot to prevent black screens. But there will still be exceptions.

**Comment by KARPED1EM** [comment]
Host-only has been fighting the black screen problem. For example, TOHR has a lot of black screen problems. TOH+ can't even play on Airship map

**Comment by KARPED1EM** [comment]
It's all about translation work.  Not translated or mistranslated

**Comment by KARPED1EM** [comment]
![Screenshot_2023-05-06-04-44-27-903_com.android.chrome-edit.jpg](https://user-images.githubusercontent.com/89320463/236565386-57e35b9d-92d1-4dbb-9074-69ea279d4ffc.jpg)

**Comment by KARPED1EM** [comment]
Debug is for mod devs and devs of other TOHE branches

**Comment by KARPED1EM** [comment]
Translation issue has been resolved, please wait for updates
