### ISSUE TITLE
哈哈没错又是我

### ISSUE THREAD

**Issue by Sand-and-Beans** [KARPED1EM/TownOfHostEdited#134]
我又来提建议了
1. 如下图（小建议）
![2023-05-06](https://user-images.githubusercontent.com/129944434/236617768-a1e638e8-61f1-43b5-b888-81d38a5fc7b5.png)
2. 我知道隐蔽者是试验性职业，但是我只是想提醒一下，有一个小bug，通讯破坏后，隐蔽者就没法发动技能了，其他的昨天玩了好几局除了游戏本身的bug以外没啥问题。
3. 理论上来讲中立和内鬼也应该看到任务吧，不然通用任务是啥不知道了。
4. 只剩下叛徒和船员时，游戏不会结束。

**Comment by KARPED1EM** [comment]
1. 整那么多分类看着不烦吗，以后还要加东西，到时候一个选项一个分类？
2. 通讯破坏黑人与隐蔽技能共存，职业说明有提到。
4. ![Screenshot_2023-05-07-05-47-58-978_com.github.android-edit.jpg](https://user-images.githubusercontent.com/89320463/236647898-9ae89bde-3929-4328-8f83-f6688eacde65.jpg)

![Screenshot_2023-05-07-05-51-09-517_com.discord.png](https://user-images.githubusercontent.com/89320463/236647927-b87740ea-64fa-4c09-a210-d306c5e52248.png)
