### ISSUE TITLE
Game lags mid-game

### ISSUE THREAD

**Issue by JrGamer410** [KARPED1EM/TownOfHostEdited#139]
While the game is playing, the game will lag around every 5 seconds. This issue is not present while in lobby or menus. The /dump command doesn't work either

**Comment by KARPED1EM** [comment]
The host-only mods has a big disadvantage, that is, in order to achieve host-only, the host has to help the other 14 people to complete the calculation, which will require the hsot's computer to have better performance. Of course, we gave you a low load option to optimize performance.
