### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by Blykey** [KARPED1EM/TownOfHostEdited#154]
I recently came back after not playing TOHe  for a while and when I installed the new version and started the game it kept crashing.

**Comment by Tommy-XL** [comment]
This version of TOHE is no longer supported, but fortunately there is a continuation of the mod that is already supported by other developers: https://github.com/0xDrMoe/TownofHost-Enhanced

**Comment by Sand-and-Beans** [comment]
It's not supported now. You can wait for the development of TONX (the official continuation of TOHE) or play other mods.
