### ISSUE TITLE
Help in translation

### ISSUE THREAD

**Issue by Tommy-XL** [KARPED1EM/TownOfHostEdited#17]
Please explain what this setting does, because when you try to translate from Chinese, the translation becomes incomprehensible and it is not clear what exactly it does

![image](https://user-images.githubusercontent.com/104814436/218395245-e835ec49-8704-4451-aced-4e0048e83863.png)

**Comment by KARPED1EM** [comment]
`SendCodeToQQ`
`SendCodeMinPlayer`

Those options is disabled when the player's region is not China

When this option is turned on, the lobby code will be sent to our QQ group (similar to Discord), so that players can easily find game which uses TOHE

**Comment by Tommy-XL** [comment]
Oh, so that's what this setting is, so I'll add a note to the translation

And for now, do not close the question, maybe I will have more questions, and if not, then I will close the question myself
