### ISSUE TITLE
Role idea: Transporter

### ISSUE THREAD

**Issue by Tommy-XL** [KARPED1EM/TownOfHostEdited#18]
Role idea: Transporter
Team: Crewmate

Ability:
When he completes one task, he will be able to randomly swap 2 alive players (including himself).

Settings: 
Max number of teleport: Min - 1, Max - 6. 
Edit Transporter Tasks

**Comment by Tommy-XL** [comment]
As for me, this role is interesting and not very strong from the point of view of balance, so I will be glad if it is eventually implemented

**Comment by KARPED1EM** [comment]
The idea sounds great. In fact, my original intention of making this mod is to have fun
However, teleportation seems to only work when the player is not moving, such as assassins and miners
I need time to test and if it works I will make this role

**Comment by Tommy-XL** [comment]
Hmm, if teleport is not possible when the player is moving, is it possible to make these 2 players freeze for 0.5 seconds before teleporting (like when Impostor kills Trapper) and they both swap places

**Comment by KARPED1EM** [comment]
Good idea, I'll try it when I'm uplead the next version

**Comment by KARPED1EM** [comment]
The Transporter has been made
Please tell me a color you like, I will use this color for this character's name

**Comment by Tommy-XL** [comment]
I think this color would work best: #42D1FF

**Comment by KARPED1EM** [comment]
Transporter has been added to the latest version
https://github.com/KARPED1EM/TownOfHostEdited/releases/tag/v1.2.0
