### ISSUE TITLE
Unknown message

### ISSUE THREAD

**Issue by Tommy-XL** [KARPED1EM/TownOfHostEdited#29]
Sometimes a message appears which cannot be translated to string.csv

![IMG_20230221_081437_826](https://user-images.githubusercontent.com/104814436/220216379-4cf43f92-2386-4dd3-af94-8769a27acda6.jpg)

**Comment by KARPED1EM** [comment]
OK ill fix it later
btw, recently some android players in China get `Disconnected from server due to an error` when game start
is it same in Rassua?

**Comment by Tommy-XL** [comment]
Yes, this has been happening for a long time and very often, usually it happens with those players who have a weak Internet. Therefore, we usually play in the Asia region, and not in Europe, in Asia it happens less often, but still there are exceptions. (Region Europe is considered as the main one for us)

**Comment by KARPED1EM** [comment]
I added more text to support translation in the csv
