### ISSUE TITLE
不错的TownOfHost Frok

### ISSUE THREAD

**Issue by commandf1** [KARPED1EM/TownOfHostEdited#3]
很不错的fork
我想要一个java语言的among us开发框架
您知道目前有这个框架吗？

**Comment by KARPED1EM** [comment]
感谢您的支持，不过我目前对unity游戏的mod开发还不是很了解。我并不清楚是否存在可以开发AU模组的java语言的框架。
很抱歉没能给您提供有用的信息，不过如果您在C#开发AU模组的时候遇到问题欢迎随时来和我讨论。
