### ISSUE TITLE
Lighter does not work

### ISSUE THREAD

**Issue by Tommy-XL** [KARPED1EM/TownOfHostEdited#30]
In the screenshot, White and Purple have Add-ons "Lighter"

![bug111](https://user-images.githubusercontent.com/104814436/220273535-2bf596d5-6cc3-4265-b5b7-7ca6d02c42c4.jpg)
![bug222](https://user-images.githubusercontent.com/104814436/220273544-ec8d06eb-8fca-4334-9870-cf4b05a28202.jpg)

Note: "Фонарик" in English will be like "Lighter"
![bug333](https://user-images.githubusercontent.com/104814436/220273546-777024b8-d4c7-4920-9186-172ed8a6b69c.jpg)

**Comment by KARPED1EM** [comment]
thanks for your feedback, it fixed
