### ISSUE TITLE
Add-ons Madmate And Transporter 

### ISSUE THREAD

**Issue by Tommy-XL** [KARPED1EM/TownOfHostEdited#32]
Transporter has no task when given Add-ons Madmate, so his ability won't work

![IMG_20230221_204321](https://user-images.githubusercontent.com/104814436/220348397-2b2a2c8d-c322-4169-b234-dafea19294e4.jpg)

**Comment by KARPED1EM** [comment]
Fixed, Madmate Transporter has tasks now
