### ISSUE TITLE
Question about Translation

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#35]
![image](https://user-images.githubusercontent.com/107776037/220620166-284e4ece-39f9-421f-a7f5-eebb84b2c6c2.png)
Is there a way to translate it in English? All i got is 
`Welcome to the PC
Nothing more, just a more urgent version independent`

**Comment by KARPED1EM** [comment]
In fact, this is an announcement, obtained through the Internet, not attached to the game content.
Maybe future announcements will have an English version, but languages other than Chinese and English will not be supported.
