### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#37]
While at meeting, there can be a chance that body of Host will be reported. For some reason, Host is always alive at that moment, and there are no Paranoia roles. 
![image](https://user-images.githubusercontent.com/107776037/220740138-4cab9dc8-4a42-475f-901e-80c3f5597afa.png)

**Comment by KARPED1EM** [comment]
You mean the host sometimes reports thier own body, then the meeting starts but no one dies?
If there is no Paranoia, it may be because the host uses the command hotkey <kbd>Shift</kbd> + <kbd>R</kbd> + <kbd>Enter</kbd>
This hotkey is for the host to hold an emergency meeting in TOHE

**Comment by mogekonik1** [comment]
Yeah, that's maybe the reason. But maybe change it to something else? Because i use Shift + R + Enter a lot of times..

**Comment by KARPED1EM** [comment]
haha, What is this key used for?

**Comment by mogekonik1** [comment]
> haha, What is this key used for?

In Russian, if i wanna say word "Кстати" i usually press Shift + R, and maybe at that time, there was Enter by accident.

**Comment by KARPED1EM** [comment]
well this hotkey will be canceled in the next version
