### ISSUE TITLE
God wins even if with love in someone.

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#41]
![image](https://user-images.githubusercontent.com/107776037/221378337-fda874d8-833b-4e8b-bc2f-fd092d789b77.png)
Is it supposed to happen that way?

**Comment by mogekonik1** [comment]
White - Won - Alive - God + Lovers 
Pink - Lost -  Alive - + Lovers 
Rose - Killed herself - Sheriff + Lighter 
Red - Killed - Snitch 
Cyan - Kicked - Arrogance 
Purple - Killed - Terrorist 
Black - Kicked - Madmate Transporter 
Banana - Kicked - Anti Adminer + Tie-Breaker
Gray - Killed - Jackal 
Lime - Killed - Mayor 
Tan - Killed - Bait 
Corall - Quitted - Jester 
Blue - Kicked - Luckey

**Comment by KARPED1EM** [comment]
The God won't be lover in next version
