### ISSUE TITLE
Russian mixed up with Chinese

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#42]
![image](https://user-images.githubusercontent.com/107776037/221437519-98cc9dd8-91d0-435b-a290-68e376db1a61.png)
Orange was kicked, but we saw Chinese and Russian. Maybe something happened in translation?

**Comment by Tommy-XL** [comment]
I think this happens even in English translation

**Comment by KARPED1EM** [comment]
It's ok in next version
pls wait for the translation
@Tommy-XL
