### ISSUE TITLE
Text Aspect / 文字方面

### ISSUE THREAD

**Issue by borjita2019** [KARPED1EM/TownOfHostEdited#43]
Hello, it seems that these texts are not working properly. The texts look like this. *TabGroup.Imposters *Commands.dump and cannot be read correctly.

你好，这些文本似乎不能正常工作。这些文本是这样的。*TabGroup.Imposters *Commands.dump，无法正常阅读。

**Comment by KARPED1EM** [comment]
where did you get those text?

**Comment by Tommy-XL** [comment]
There is only:

"TabGroup.ImpostorRoles" 
"Command.dump"

**Comment by borjita2019** [comment]
> where did you get those text?

everywhere that had a title / description

**Comment by KARPED1EM** [comment]
Do you mean the settings menu or something else

**Comment by borjita2019** [comment]
in-lobby tohe settings, kill reason, command descriptions using /help

**Comment by KARPED1EM** [comment]
I've checked the those strings, but can't seem to find the problem
Please wait for the new version and check again

**Comment by borjita2019** [comment]
imma send a screenshot wait

**Comment by borjita2019** [comment]
reopen this pls

**Comment by borjita2019** [comment]
![imagen](https://user-images.githubusercontent.com/63255187/222915665-7292b4f6-f642-44fd-a317-a1a439434e46.png)
![imagen](https://user-images.githubusercontent.com/63255187/222915677-6116903c-d9cc-4ef3-af95-d59836393128.png)
![imagen](https://user-images.githubusercontent.com/63255187/222915684-e776d227-dc1c-4bb4-89db-b7f2e9a16d01.png)
![imagen](https://user-images.githubusercontent.com/63255187/222915690-fb5a3161-376f-4fed-95e4-e2e54cd58e13.png)
![imagen](https://user-images.githubusercontent.com/63255187/222915694-f08da97a-75e0-437f-a81a-ffd36551c385.png)
![imagen](https://user-images.githubusercontent.com/63255187/222915699-0455d706-1ff1-42ad-8b3b-a05914ab755d.png)

**Comment by borjita2019** [comment]
![imagen](https://user-images.githubusercontent.com/63255187/222915705-345328ff-2755-413b-8984-05d3234866e1.png)

**Comment by KARPED1EM** [comment]
What language do you use in game?

**Comment by borjita2019** [comment]
English or Spanish

**Comment by KARPED1EM** [comment]
oh, unfortunately tohe doesn't support Spanish
switch game language to English
then it will display English normally
