### ISSUE TITLE
Icons move in menu

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#54]
![image](https://user-images.githubusercontent.com/107776037/222980840-20f47299-688f-4e89-b102-51868eece06c.png)
![image](https://user-images.githubusercontent.com/107776037/222980849-9f121c91-3db2-4fbb-bd8e-9a69c7d94a61.png)
If you stand far away from notebook, you will move icons in menu.

**Comment by Huier-Huang** [comment]
> ![image](https://user-images.githubusercontent.com/107776037/222980840-20f47299-688f-4e89-b102-51868eece06c.png) ![image](https://user-images.githubusercontent.com/107776037/222980849-9f121c91-3db2-4fbb-bd8e-9a69c7d94a61.png) If you stand far away from notebook, you will move icons in menu.

I have submitted a fix patch in #57 and will fix it in the next release
