### ISSUE TITLE
Divinator gets this error when trying to vote himself

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#55]
![image](https://user-images.githubusercontent.com/107776037/222989830-d1ef5339-362a-4149-a6ff-c1c227e5856b.png)
[TOHE-v2.1.1-2023-03-05_23.36.44.log](https://github.com/KARPED1EM/TownOfHostEdited/files/10893131/TOHE-v2.1.1-2023-03-05_23.36.44.log)

**Comment by KARPED1EM** [comment]
Thanx for your feedback.
it has been fixed
