### ISSUE TITLE
Impostor chat

### ISSUE THREAD

**Issue by borjita2019** [KARPED1EM/TownOfHostEdited#56]
I would love a feature that when typing "/imp" or "!" at the start of the message, only imposters can see that message (Like a chat for imposters only) so they can talk about plans and stuff, the name changes to "<name> (IMP CHAT)" so they would know the imposters are seeing it only

**Comment by borjita2019** [comment]
If your going to add this sometime, please make the "/imp" one toggleable (you toggle between global chat and imp chat)

**Comment by KARPED1EM** [comment]
We also want to let lovers or imp talk privately. 
But this is not possible in the host only mods.
Cause we can't prevent players without mod from receiving messages.
