### ISSUE TITLE
Mad Time Master can't do tasks

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#61]
![image](https://user-images.githubusercontent.com/107776037/224043699-c9ef8aa4-cb2a-44b4-ac8c-62694c4af239.png)
![photo_2023-03-09_14-43-44](https://user-images.githubusercontent.com/107776037/224044930-631526db-3524-4412-a208-e15620cd1b6c.jpg)

Same problem as Transporter (well in past)

**Comment by mogekonik1** [comment]
[TOHE-v2.1.4-2023-03-13_18.36.43.log](https://github.com/KARPED1EM/TownOfHostEdited/files/10960034/TOHE-v2.1.4-2023-03-13_18.36.43.log)
Updated, you can do tasks on Vanila, but it just doesn't work.

**Comment by KARPED1EM** [comment]
Thx, it fixed, plz wait for next version
