### ISSUE TITLE
关于TOH的通病

### ISSUE THREAD

**Issue by InvincibleFool** [KARPED1EM/TownOfHostEdited#63]
现在AUS几乎所有房间都是TOH及分支房间了,这回带来一些问题:
1 职业阵营问题 就这么说吧,没玩过TOH房间的人知道警长实际上是好人吗?知道独裁者投票后会死亡吗?知道恐怖分子是坏人吗?
他们不会知道的,而且就说"不会玩的请走开"也会有"没有原版房间"的这个问题
所以,我希望将职业介绍 即 职业的第二行 改为 [阵营(中立的话就写 中立 坏人)]+技能&效果,虽然会议中可以用/m,但还是那句话"没有玩过的根本不会主动用/m"

2对应第一点"没有原版房间" 我其实希望让TOH及其所有分支 都强制使用"休闲"这一个房间类型,至于为什么?我相信作者您更清楚了吧

还有,TOHE做的不错

**Comment by KARPED1EM** [comment]
hmm, kinda tough decision
tt can be said that the risks of doing so outweigh the benefits

They don't need to know about their team if they don't even use /m to check role abilities
it's no use to them either u know
