### ISSUE TITLE
No chat for Host

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#71]
![image](https://user-images.githubusercontent.com/107776037/225953623-97b4c5be-7406-4a61-8efc-5266846558e7.png)
[TOHE-v2.1.5-2023-03-17_16.47.07.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11003110/TOHE-v2.1.5-2023-03-17_16.47.07.log)

**Comment by KARPED1EM** [comment]
thanks so much for ur log

**Comment by KARPED1EM** [comment]
Fixed
