### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#72]
[TOHE-v2.1.5-2023-03-17_18.11.27.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11004050/TOHE-v2.1.5-2023-03-17_18.11.27.log)
At the end of the log, there is a lot of object which were not set.

**Comment by KARPED1EM** [comment]
because of it [#71](https://github.com/KARPED1EM/TownOfHostEdited/issues/71)
