### ISSUE TITLE
Settings got bugged A LOT!

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#74]
![image](https://user-images.githubusercontent.com/107776037/227735731-f8b393df-edb2-4600-9b7f-d7bdf5862ac5.png)
![image](https://user-images.githubusercontent.com/107776037/227735747-d0f8d91d-0025-4657-84a3-5ed3951dd08d.png)
![image](https://user-images.githubusercontent.com/107776037/227735776-0af0334b-c1ab-477c-9e74-6156ea78d284.png)
![image](https://user-images.githubusercontent.com/107776037/227735786-bd99821e-8fa7-4276-a37c-133f3c1cfde8.png)

**Comment by mogekonik1** [comment]
![image](https://user-images.githubusercontent.com/107776037/227736135-b1880d71-4549-4f7e-88fe-074f456de7f4.png)
![image](https://user-images.githubusercontent.com/107776037/227736142-f5cd3f09-f6e2-4112-b602-8f3c6f01762e.png)
![image](https://user-images.githubusercontent.com/107776037/227736151-4a7ba45d-6688-4000-8cc9-e477654aef87.png)

**Comment by KARPED1EM** [comment]
hmm, we have no translation for a lot of text so far

**Comment by Tommy-XL** [comment]
There is no text because I have not yet translated new versions, as soon as I have time I will translate all the settings and roles

**Comment by KARPED1EM** [comment]
> There is no text because I have not yet translated new versions, as soon as I have time I will translate all the settings and roles

Thanks too much
btw would you like a developer tag?
![image](https://user-images.githubusercontent.com/89320463/227765621-ef0f2428-5323-4f1e-b121-2052332648ed.png)

**Comment by Tommy-XL** [comment]
Hmm that would be nice, I think it requires my friend code:
keepchirpy#6354

**Comment by KARPED1EM** [comment]
> Hmm that would be nice, I think it requires my friend code:
> keepchirpy#6354

Great! and what color and text you want

**Comment by Tommy-XL** [comment]
#E42217
