### ISSUE TITLE
Practice doesn't work, and doesn't scroll down

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#76]
![image](https://user-images.githubusercontent.com/107776037/227737158-2b30d7a0-484c-432b-92e1-3f433116b2c3.png)

**Comment by mogekonik1** [comment]
also you can't kill or vent*

**Comment by KARPED1EM** [comment]
oh we didn't mean to add these in free mode.
these appear here because of some coincidence reason of developing, so it never work.
