### ISSUE TITLE
Icon of a vent disappears if vent, but appears in vent

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#77]
![image](https://user-images.githubusercontent.com/107776037/227737328-11003ffd-82c9-479d-b551-d792f3da5c1d.png)
![image](https://user-images.githubusercontent.com/107776037/227737429-6f7c6aae-74ac-4046-b1c7-da2e42b40bfb.png)

**Comment by KARPED1EM** [comment]
Fixed in mod
but it can't fix in vanilla client cause of technical limitations
