### ISSUE TITLE
Black screen if use "Show Addons" option

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#78]
[TOHE-v2.2.2-2023-03-26_19.03.28.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11072371/TOHE-v2.2.2-2023-03-26_19.03.28.log)

**Comment by mogekonik1** [comment]
False alarm, I did my translation wrong..

**Comment by KARPED1EM** [comment]
To prevent errors in translation files.  I added a log that will tell us where things go wrong.  You can check through the log, hope this can help you.
![Screenshot_2023-03-27-01-15-31-890_com.android.chrome-edit.jpg](https://user-images.githubusercontent.com/89320463/227792608-a23211ca-bfd6-4a13-9bec-09df71a96021.jpg)
