### ISSUE TITLE
Android user has "Town of Host" error

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#80]
![изображение_2023-03-27_215544868](https://user-images.githubusercontent.com/107776037/228052104-7643bdf9-49c6-49c0-8297-62913f2cfe46.png)
[TOHE-v2.2.2-2023-03-27_21.54.27.log](https://github.com/KARPED1EM/TownOfHostEdited/files/11082495/TOHE-v2.2.2-2023-03-27_21.54.27.log)
This person "has Town of Host" but actually playing on the phone.

**Comment by KARPED1EM** [comment]
Fixed and thanks
