### ISSUE TITLE
卧底的方案

### ISSUE THREAD

**Issue by InvincibleFool** [KARPED1EM/TownOfHostEdited#86]
为什么不将所有的内鬼像豺狼那样单独分配 并在游戏中将其他内鬼和卧底的名字改为红色?
像 警长 可以杀死 红色名字的梦魔 那样?

**Comment by XiezibanWrite** [comment]
话说你这建议感觉有点。。。不太可能实现

**Comment by XiezibanWrite** [comment]
如果真的独立分配的话 卧底不能跟内鬼显示在同一个显示职业的界面啊 但凡内鬼仔细记下职业显示的界面的队友 卧底不就不找自出了么

**Comment by InvincibleFool** [comment]
> 如果真的独立分配的话 卧底不能跟内鬼显示在同一个显示职业的界面啊 但凡内鬼仔细记下职业显示的界面的队友 卧底不就不找自出了么

错误的,让内鬼的分配变为豺狼那样(即只显示自己一个人),在游戏中把其他的队友和卧底改名字(参考梦魔或本家猫的灰色名字)

**Comment by XiezibanWrite** [comment]
> > 如果真的独立分配的话 卧底不能跟内鬼显示在同一个显示职业的界面啊 但凡内鬼仔细记下职业显示的界面的队友 卧底不就不找自出了么
> 
> 错误的,让内鬼的分配变为豺狼那样(即只显示自己一个人),在游戏中把其他的队友和卧底改名字(参考梦魔或本家猫的灰色名字)

hmm 改名字有什么用？改了也不是真内鬼 也没办法让他们理解错

**Comment by InvincibleFool** [comment]
> > > 如果真的独立分配的话 卧底不能跟内鬼显示在同一个显示职业的界面啊 但凡内鬼仔细记下职业显示的界面的队友 卧底不就不找自出了么
> > 
> > 
> > 错误的,让内鬼的分配变为豺狼那样(即只显示自己一个人),在游戏中把其他的队友和卧底改名字(参考梦魔或本家猫的灰色名字)
> 
> hmm 改名字有什么用？改了也不是真内鬼 也没办法让他们理解错

你理解错了吧,假如你使用原版客户端进入,分配时如果出现职业"卧底",那么你在开局的时候(即原版哪里显示"伪装者")时,只显示你自己一个人(像豺狼 警长 纵火犯 FFF团 侠客 赝品商 也就是在开局看不见队友)等到进入游戏后 由 系统修改玩家名字(即在自由活动时间时 才将 卧底 和 内鬼队友 的名字改为 红名) 这样的话您是很难分辨那个是真的队友的

**Comment by KARPED1EM** [comment]
卧底曾在4022版本完成制作，经测试没有你们所描述的问题。但最后该职业因无法实现内鬼互相击杀而被废稿。

顺带一提，由于在那之后进行了一次代码完全重构并切换了分支，导致卧底的代码已丢失。

**Comment by KARPED1EM** [comment]
> 为什么不将所有的内鬼像豺狼那样单独分配 并在游戏中将其他内鬼和卧底的名字改为红色?
> 像 警长 可以杀死 红色名字的梦魔 那样?

中立带刀职业如此设计的原理是利用客户端与服务端的信息差，也就是让豺狼本人以为自己是狼因此显示了击杀按钮，可以像服务器发送击杀请求，而房主视角下豺狼还是被注册为普通船员，只是受理了来自普通船员的击杀请求以完成击杀操作。

如果将所有内鬼如此分配，则原版端以及服务器会认为场上从未存在过内鬼，这会引起很多致命的问题。

从技术上来讲，我们可以实现，但为一个职业改变整个内鬼的存在机制，其工作量以及收益不成正比，得不偿失。请试着从开发的角度看待问题。
