### ISSUE TITLE
Suggestion: Add Max Number of Ability Uses for Veteran

### ISSUE THREAD

**Issue by Gurge44** [KARPED1EM/TownOfHostEdited#93]

**Comment by Gurge44** [comment]
Also thank you for this amazing mod, it made me want to play Among Us again!

**Comment by KARPED1EM** [comment]
Really, I can't believe you can rate it so highly lol
thx so much

**Comment by KARPED1EM** [comment]
and i'll add this option in next version as you want

**Comment by KARPED1EM** [comment]
Added To Dev Version
