### ISSUE TITLE
No space between nickname and "Survived"

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#95]
![image](https://user-images.githubusercontent.com/107776037/231535507-85ec0b6f-a828-4317-9cc1-cdd346d17e6d.png)
Information about player:
  modSurvived No-
  BANANASurvived Witch

**Comment by mogekonik1** [comment]
![image](https://user-images.githubusercontent.com/107776037/231547065-1d8a8ae7-e4fb-4459-a6ac-eb5df78c1973.png)

**Comment by KARPED1EM** [comment]
![image](https://user-images.githubusercontent.com/89320463/231818624-d4550c85-437b-45fb-9f52-8fc431105ee6.png)
![image](https://user-images.githubusercontent.com/89320463/231819222-ea312d71-9260-49c0-81e7-539b952420bc.png)

**Comment by KARPED1EM** [comment]
Fixed
