### ISSUE TITLE
Idea: Custom place for logs, not just in desktop.

### ISSUE THREAD

**Issue by mogekonik1** [KARPED1EM/TownOfHostEdited#97]
please, 
![image](https://user-images.githubusercontent.com/107776037/231602969-01939e82-db8f-4c7b-97af-8680b627b8cb.png)
it's just very annoing for everyone. Maybe change it in TOHE settings? Or TOHE_DATA will have "Logs" or smh

**Comment by KARPED1EM** [comment]
like create a folder before output logs or sth?

**Comment by mogekonik1** [comment]
yeah, something kind of that
