### ISSUE TITLE
新选项 New Options

### ISSUE THREAD

**Issue by Sand-and-Beans** [KARPED1EM/TownOfHostEdited#98]
众所周知利己总是会在人们意想不到的时候胜利，就有很多人觉得利己破坏了游戏的公平性，以至于大家都觉得这个职业很”废“（从某些意义上来讲）。我有如下的建议：
增加选项（看起来就像下面这样）
利己主义者                                                - 启用 +
最大人数                                                    -   1   +
出现概率                                                    - 65% +
内鬼可以成为利己主义者                          - 开启 +
船员可以成为利己主义者                          - 开启 +
       显示谁是利己主义者                          - 开启 +
               剩余多少人时显示利己主义者    -   3   +
注：显示利己主义者就是指像大明星一样，所有玩家视野中利己主义者名字会变成蓝紫色

然后资本家也被大家公认为废物职业，我有如下的建议：
增加选项（看起来就像下面这样）
资本家                                                        - 启用 +
最大人数                                                     -   1   +
可以击杀                                                    - 开启 +
技能冷却时间                                             - 30秒 +

同时想要说一下，隐蔽者、愚者和革命家的bug还存在
谢谢

As we all know, egoist always win unexpectedly. This causes that many people believe that egoist break the balance of the game. Many people think egoist is a "rubbish" role (from some aways). I have some suggestions below: 
Add options (Looks like this) 
Egoist                                                      -Active+
Max                                                         -    1    +
Spawn Chance                                        -  65% +
Imposter can become Egoist                  -  ON  +
Crewmate can become Egoist                -  ON  +
        Everyone knows who is an Egoist   -  ON  +
               Applied living player count      -   3   +
PS: Option "Every knows who is an Egoist" is like the Super Star, Egoist's name will become dark blue in everyone's sight. 

Also, capitalist is also known as a "rubbish" role. I have some suggestions below: 
Add options (Looks like this)
Capitalist                                                 -Active+
Max                                                         -    1    +
Can kill                                                    -  ON  +
Skill cooldown                                         -  30s  +

And at last, I want to say that Concealer, Psychic, and Revolutionist's bugs are still existing. 
Thks

**Comment by KARPED1EM** [comment]
有一说一，你为什么英语和中文都这么好

**Comment by Sand-and-Beans** [comment]
> 有一说一，你为什么英语和中文都这么好

呃，英语好是因为我学校比较注重英语教学（估计也就这个特色了吧），关于中文为什么这么好因为我本来就是中国人😊
